#############################################################################
# Makefile for building: GPUnit-UI.app/Contents/MacOS/GPUnit-UI
# Generated by qmake (2.01a) (Qt 4.6.3) on: Mon Nov 1 15:11:30 2010
# Project:  GPUnit-UI.pro
# Template: app
# Command: /opt/local/bin/qmake -spec /opt/local/libexec/qt4-mac/mkspecs/macx-g++ -macx CONFIG+=debug -o Makefile GPUnit-UI.pro
#############################################################################

####### Compiler, tools and options

CC            = /usr/bin/gcc-4.2
CXX           = /usr/bin/g++-4.2
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
INCPATH       = -I/opt/local/libexec/qt4-mac/mkspecs/macx-g++ -I. -I/opt/local/libexec/qt4-mac/lib/QtCore.framework/Versions/4/Headers -I/opt/local/libexec/qt4-mac/lib/QtCore.framework/Versions/4/Headers -I/opt/local/libexec/qt4-mac/lib/QtGui.framework/Versions/4/Headers -I/opt/local/libexec/qt4-mac/lib/QtGui.framework/Versions/4/Headers -I/opt/local/libexec/qt4-mac/include -I. -I. -F/opt/local/libexec/qt4-mac/lib
LINK          = /usr/bin/g++-4.2
LFLAGS        = -headerpad_max_install_names -arch i386
LIBS          = $(SUBLIBS) -F/opt/local/libexec/qt4-mac/lib -L/opt/local/libexec/qt4-mac/lib -framework QtGui -L/opt/local/libexec/qt4-mac/lib -F/opt/local/libexec/qt4-mac/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /opt/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		moduleeditor.cpp \
		modulestoolbox.cpp moc_mainwindow.cpp \
		moc_moduleeditor.cpp \
		moc_modulestoolbox.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moduleeditor.o \
		modulestoolbox.o \
		moc_mainwindow.o \
		moc_moduleeditor.o \
		moc_modulestoolbox.o
DIST          = /opt/local/libexec/qt4-mac/mkspecs/common/unix.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac-g++.conf \
		/opt/local/libexec/qt4-mac/mkspecs/qconfig.pri \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_functions.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_config.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/exclusive_builds.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/dwarf2.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/debug.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/x86.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/objective_c.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/warn_on.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/unix/thread.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/moc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/rez.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/sdk.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/resources.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/uic.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/yacc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/lex.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/include_source_dir.prf \
		GPUnit-UI.pro
QMAKE_TARGET  = GPUnit-UI
DESTDIR       = 
TARGET        = GPUnit-UI.app/Contents/MacOS/GPUnit-UI

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		i386 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile GPUnit-UI.app/Contents/PkgInfo GPUnit-UI.app/Contents/Resources/empty.lproj GPUnit-UI.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h ui_moduleeditor.h ui_modulestoolbox.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) GPUnit-UI.app/Contents/MacOS/ || $(MKDIR) GPUnit-UI.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GPUnit-UI.pro  /opt/local/libexec/qt4-mac/mkspecs/macx-g++/qmake.conf /opt/local/libexec/qt4-mac/mkspecs/common/unix.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac-g++.conf \
		/opt/local/libexec/qt4-mac/mkspecs/qconfig.pri \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_functions.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_config.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/exclusive_builds.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/dwarf2.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/debug.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/x86.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/objective_c.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/warn_on.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/unix/thread.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/moc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/rez.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/sdk.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/resources.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/uic.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/yacc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/lex.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/include_source_dir.prf \
		/opt/local/libexec/qt4-mac/lib/QtGui.framework/QtGui.prl \
		/opt/local/libexec/qt4-mac/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /opt/local/libexec/qt4-mac/mkspecs/macx-g++ -macx CONFIG+=debug -o Makefile GPUnit-UI.pro
/opt/local/libexec/qt4-mac/mkspecs/common/unix.conf:
/opt/local/libexec/qt4-mac/mkspecs/common/mac.conf:
/opt/local/libexec/qt4-mac/mkspecs/common/mac-g++.conf:
/opt/local/libexec/qt4-mac/mkspecs/qconfig.pri:
/opt/local/libexec/qt4-mac/mkspecs/features/qt_functions.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/qt_config.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/exclusive_builds.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/default_pre.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_pre.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/dwarf2.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/debug.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/default_post.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_post.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/x86.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/objective_c.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/warn_on.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/qt.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/unix/thread.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/moc.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/rez.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/sdk.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/resources.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/uic.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/yacc.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/lex.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/include_source_dir.prf:
/opt/local/libexec/qt4-mac/lib/QtGui.framework/QtGui.prl:
/opt/local/libexec/qt4-mac/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/local/libexec/qt4-mac/mkspecs/macx-g++ -macx CONFIG+=debug -o Makefile GPUnit-UI.pro

GPUnit-UI.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) GPUnit-UI.app/Contents || $(MKDIR) GPUnit-UI.app/Contents 
	@$(DEL_FILE) GPUnit-UI.app/Contents/PkgInfo
	@echo "APPL????" >GPUnit-UI.app/Contents/PkgInfo
GPUnit-UI.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) GPUnit-UI.app/Contents/Resources || $(MKDIR) GPUnit-UI.app/Contents/Resources 
	@touch GPUnit-UI.app/Contents/Resources/empty.lproj
	
GPUnit-UI.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) GPUnit-UI.app/Contents || $(MKDIR) GPUnit-UI.app/Contents 
	@$(DEL_FILE) GPUnit-UI.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,GPUnit-UI,g" -e "s,@TYPEINFO@,????,g" /opt/local/libexec/qt4-mac/mkspecs/macx-g++/Info.plist.app >GPUnit-UI.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/GPUnit-UI1.0.0 || $(MKDIR) .tmp/GPUnit-UI1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GPUnit-UI1.0.0/ && $(COPY_FILE) --parents mainwindow.h moduleeditor.h modulestoolbox.h .tmp/GPUnit-UI1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp moduleeditor.cpp modulestoolbox.cpp .tmp/GPUnit-UI1.0.0/ && $(COPY_FILE) --parents mainwindow.ui moduleeditor.ui modulestoolbox.ui .tmp/GPUnit-UI1.0.0/ && (cd `dirname .tmp/GPUnit-UI1.0.0` && $(TAR) GPUnit-UI1.0.0.tar GPUnit-UI1.0.0 && $(COMPRESS) GPUnit-UI1.0.0.tar) && $(MOVE) `dirname .tmp/GPUnit-UI1.0.0`/GPUnit-UI1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GPUnit-UI1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r GPUnit-UI.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_moduleeditor.cpp moc_modulestoolbox.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_moduleeditor.cpp moc_modulestoolbox.cpp
moc_mainwindow.cpp: moduleeditor.h \
		mainwindow.h
	/opt/local/libexec/qt4-mac/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_moduleeditor.cpp: moduleeditor.h
	/opt/local/libexec/qt4-mac/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ moduleeditor.h -o moc_moduleeditor.cpp

moc_modulestoolbox.cpp: modulestoolbox.h
	/opt/local/libexec/qt4-mac/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ modulestoolbox.h -o moc_modulestoolbox.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_moduleeditor.h ui_modulestoolbox.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_moduleeditor.h ui_modulestoolbox.h
ui_mainwindow.h: mainwindow.ui \
		modulestoolbox.h
	/opt/local/libexec/qt4-mac/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_moduleeditor.h: moduleeditor.ui
	/opt/local/libexec/qt4-mac/bin/uic moduleeditor.ui -o ui_moduleeditor.h

ui_modulestoolbox.h: modulestoolbox.ui
	/opt/local/libexec/qt4-mac/bin/uic modulestoolbox.ui -o ui_modulestoolbox.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		moduleeditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		moduleeditor.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moduleeditor.o: moduleeditor.cpp moduleeditor.h \
		ui_moduleeditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moduleeditor.o moduleeditor.cpp

modulestoolbox.o: modulestoolbox.cpp modulestoolbox.h \
		ui_modulestoolbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modulestoolbox.o modulestoolbox.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_moduleeditor.o: moc_moduleeditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_moduleeditor.o moc_moduleeditor.cpp

moc_modulestoolbox.o: moc_modulestoolbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modulestoolbox.o moc_modulestoolbox.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

